# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StavTunnel < Formula
  desc "Serve the models on this machine through Stav (Stav Tunnel)"
  homepage "https://stav.ai"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rolandrabben-prog/stav-code/releases/download/v0.1.0/stav-tunnel_0.1.0_darwin_amd64.tar.gz"
      sha256 "2d61d0c2449d41227d39dc9e25fc1482704f976dfec2eca4dba662c2fa351398"

      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rolandrabben-prog/stav-code/releases/download/v0.1.0/stav-tunnel_0.1.0_darwin_arm64.tar.gz"
      sha256 "1211faff9a5e8307506917c5ed10943ad3c844445c6f4a19cf9e9a7e337364ff"

      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rolandrabben-prog/stav-code/releases/download/v0.1.0/stav-tunnel_0.1.0_linux_amd64.tar.gz"
      sha256 "d6e7d3d2bb84d2eb460789ecdc7cd716cab590c6a8113d865fdabebd9741fe73"
      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rolandrabben-prog/stav-code/releases/download/v0.1.0/stav-tunnel_0.1.0_linux_arm64.tar.gz"
      sha256 "9ac0f1a415406bc4dfd443348ce477431b809da3e2c98f203ce4d4288cb6936a"
      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
  end

  def caveats
    <<~EOS
      Enrol this machine from Connect → Tunnel in the Stav portal, then:
        stav-tunnel up --token <enrolment token>
    EOS
  end

  test do
    system "#{bin}/stav-tunnel", "version"
  end
end
