# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StavTunnel < Formula
  desc "Serve the models on this machine through Stav (Stav Tunnel)"
  homepage "https://stav.ai"
  version "0.3.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stavhq/stav-tunnel/releases/download/v0.3.0/stav-tunnel_0.3.0_darwin_amd64.tar.gz"
      sha256 "c870a74c2122fc0b2d6c1ca008bbee557fe4fc74ec6be2330fefbea3ff8cbf18"

      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stavhq/stav-tunnel/releases/download/v0.3.0/stav-tunnel_0.3.0_darwin_arm64.tar.gz"
      sha256 "7de51abff38acd2809d36f6931860d1b7685b589e7b424dfce213a663a3d7342"

      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stavhq/stav-tunnel/releases/download/v0.3.0/stav-tunnel_0.3.0_linux_amd64.tar.gz"
      sha256 "3005367f23ed73ec2aedf119c953ad4fe8456205c210ed2b15ddce786c23a9c3"
      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stavhq/stav-tunnel/releases/download/v0.3.0/stav-tunnel_0.3.0_linux_arm64.tar.gz"
      sha256 "3341d03f1c2245bab7bcb4add12c9cbd43d41db1436efba224edc7edc488e615"
      define_method(:install) do
        bin.install "stav-tunnel"
      end
    end
  end

  def caveats
    <<~EOS
      Enrol this machine from Connect → Tunnel in the Stav portal, then:
        stav-tunnel up --token <enrolment token>
    EOS
  end

  test do
    system "#{bin}/stav-tunnel", "version"
  end
end
